import {  type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

import { api, RouterOutputs } from "~/utils/api";
import MapDrawerContainer from "../components/MapDrawerContainer";

const MapWithNoSSR = dynamic(() => import('../components/MapView'), {
  ssr: false,
  loading: () => <div>Loading....</div>,
});

const Home: NextPage = () => {
 // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
    const places = api.place.getAll.useQuery({
      length: 50,
      page: 0
    }, {
      staleTime: Infinity
    })




/*
  useEffect(() => {
    const fetchPlaces = async () => {
      setPlaces(places)
    }
    fetchPlaces()
  }, [])
  */

  if(places.error || places.data == undefined){
    return <div>{JSON.stringify(places.error)}</div>
  }
 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <MapWithNoSSR places={places.data ?? null}/>
            <MapDrawerContainer >
            <div>{JSON.stringify(places.data)}</div>
            </MapDrawerContainer>
      </main>
    </>
  );
};


export default Home;
