import { Prisma } from "@prisma/client";
import { GetServerSideProps, type NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";
import { Props } from "next/script";
import { useEffect, useState } from "react";

import { api, RouterOutputs } from "~/utils/api";
import MapDrawerContainer from "./MapDrawerContainer";

interface PageProps {
  places:RouterOutputs['place']['getAll'] | null
  // Define the component's props here
}

const MapWithNoSSR = dynamic(() => import('./MapView'), {
  ssr: false,
  loading: () => <div>Loading....</div>
});


const Home: NextPage<PageProps> = () => {
 // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
    const places2 = api.place.getAll.useQuery()
  

/*
  useEffect(() => {
    const fetchPlaces = async () => {
      setPlaces(places)
    }
    fetchPlaces()
  }, [])
  */
 
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <MapWithNoSSR />
          <MapDrawerContainer places={places2?.data ?? null}/>
      </main>
    </>
  );
};


export default Home;
